// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Post struct {
	ID            uuid.UUID
	UserID        uuid.NullUUID
	TotalLikes    sql.NullInt32
	TotalComments sql.NullInt32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
