// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Photo struct {
	ID        uuid.UUID
	PhotoPath string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
}

type Post struct {
	ID            uuid.UUID
	TotalLikes    sql.NullInt32
	TotalComments sql.NullInt32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	UploadID      []byte
	UserID        uuid.UUID
}

type User struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
