// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: photos.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photos(id, user_id, post_id, photo_path, created_at, updated_at)
VALUES(
	gen_random_uuid(),
	$1,
	$2,
	$3,
	NOW(),
	NOW()
	)
RETURNING id, photo_path, created_at, updated_at, user_id, post_id
`

type CreatePhotoParams struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	PhotoPath string
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRowContext(ctx, createPhoto, arg.UserID, arg.PostID, arg.PhotoPath)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.PhotoPath,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.PostID,
	)
	return i, err
}
