// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(id, user_id, total_likes, total_comments, created_at, updated_at, upload_id)
VALUES(
	gen_random_uuid(),
	$1,
	0,
	0,
	NOW(),
	NOW(),
	$2
)
RETURNING id, total_likes, total_comments, created_at, updated_at, upload_id, user_id
`

type CreatePostParams struct {
	UserID   uuid.UUID
	UploadID []byte
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, arg.UserID, arg.UploadID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.TotalLikes,
		&i.TotalComments,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UploadID,
		&i.UserID,
	)
	return i, err
}
