// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(id, user_id, total_likes, total_comments, created_at, updated_at)
VALUES(
	gen_random_uuid(),
	$1,
	0,
	0,
	NOW(),
	NOW()
)
RETURNING id, user_id, total_likes, total_comments, created_at, updated_at
`

func (q *Queries) CreatePost(ctx context.Context, userID uuid.NullUUID) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost, userID)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalLikes,
		&i.TotalComments,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
